apiVersion: v1
kind: Service
metadata:
  name: nodejs-helloworld-service
spec:
  selector:
    app: nodejs-helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

